name: Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: 'https://www.bing.com'
    steps:
      - run: echo Hello world
      - run: sleep 20
      - run: echo 'done'
  build2:
    runs-on: ubuntu-latest
    environment: 
      name: production2
      url: 'https://www.bing.com'
    steps:
      - run: echo Hello world
      - run: sleep 20
      - run: echo 'done'
